[package]
name = "osmiumd"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
tokio = { version = "1.43.1", features = ["full"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
reqwest = { version = "0.12.11", features = ["json"] }
anyhow = "1.0.95"
